import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";
import { supabase } from "../lib/supabase";
import { useAuth } from "./AuthContext";

type Language = "de" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const translations = {
  de: {
    "nav.overview": "Übersicht",
    "nav.properties": "Immobilien",
    "nav.tenants": "Mietverhältnisse",
    "nav.payments": "Mieteingänge",
    "nav.tickets": "Tickets",
    "nav.financial": "Finanzen",
    "nav.documents": "Dokumente",
    "nav.billing": "Abrechnungen",
    "nav.account": "Account",
    "nav.languages": "Sprachen",
    "nav.logout": "Abmelden",
    "settings.profile": "Profil",
    "settings.users": "Benutzerverwaltung",
    "settings.billing": "Tarif & Abrechnung",
    "settings.feedback": "Feedback",
    "settings.language": "Sprache",
    "settings.email": "E-Mail",
    "settings.plan": "Aktueller Tarif",
    "settings.plan.free": "Kostenlos",
    "settings.plan.pro": "Professional",
    "settings.plan.enterprise": "Enterprise",
    "settings.billing.company": "Unternehmensdaten",
    "settings.billing.name": "Firmenname",
    "settings.billing.vat": "USt-IdNr.",
    "settings.billing.address": "Rechnungsadresse",
    "settings.billing.payment": "Zahlungsart",
    "settings.billing.invoices": "Rechnungen",
    "settings.users.invite": "Benutzer einladen",
    "settings.users.email": "E-Mail-Adresse",
    "settings.users.status": "Status",
    "settings.users.role": "Rolle",
    "settings.users.actions": "Aktionen",
    "settings.users.pending": "Ausstehend",
    "settings.users.accepted": "Aktiv",
    "settings.users.admin": "Administrator",
    "settings.users.member": "Mitglied",
    "settings.users.viewer": "Nur Lesezugriff",
    "settings.users.delete": "Löschen",
    "settings.users.invite.button": "Einladen",
    "settings.users.invite.success": "Einladung erfolgreich versendet",
    "settings.feedback.title": "Feature-Vorschläge & Feedback",
    "settings.feedback.description":
      "Teilen Sie uns Ihre Ideen und Verbesserungsvorschläge mit",
    "settings.feedback.idea": "Ihre Idee",
    "settings.feedback.idea.placeholder":
      "Beschreiben Sie Ihre Idee oder Ihren Verbesserungsvorschlag...",
    "settings.feedback.willing_to_pay": "Bereit dafür zu zahlen?",
    "settings.feedback.willing_to_pay.yes": "Ja",
    "settings.feedback.willing_to_pay.no": "Nein",
    "settings.feedback.amount": "Wie viel wären Sie bereit zu zahlen?",
    "settings.feedback.amount.placeholder": "z.B. 10 EUR pro Monat",
    "settings.feedback.submit": "Feedback senden",
    "settings.feedback.success": "Vielen Dank für Ihr Feedback!",
    "settings.feedback.history": "Ihr Feedback",
    "settings.feedback.date": "Datum",
    "settings.feedback.status": "Status",
    "settings.feedback.status.pending": "In Prüfung",
    "settings.feedback.status.reviewed": "Geprüft",
    "settings.feedback.status.planned": "Geplant",
    "settings.feedback.status.implemented": "Umgesetzt",
    "feedback.menu": "Feedback & Ideen",
    "feedback.title": "Feature-Vorschläge & Ideen",
    "feedback.description":
      "Teilen Sie Ihre Ideen oder stimmen Sie über bestehende Vorschläge ab",
    "feedback.submit": "Neue Idee einreichen",
    "feedback.filter.all": "Alle",
    "feedback.filter.top": "Top bewertet",
    "feedback.filter.new": "Neueste",
    "feedback.filter.mine": "Meine",
    "feedback.votes": "Stimmen",
    "feedback.no_feedback": "Noch keine Vorschläge vorhanden",
    "feedback.submit_first": "Seien Sie der Erste und teilen Sie Ihre Idee!",
    "referral.title": "Empfehlungsprogramm",
    "referral.description":
      "Empfehlen Sie Rentably und verdienen Sie Belohnungen!",
    "referral.learn_more": "Mehr erfahren",
    "footer.product": "Produkt",
    "footer.features": "Funktionen",
    "footer.pricing": "Preise",
    "footer.support": "Support",
    "footer.company": "Unternehmen",
    "footer.about": "Über uns",
    "footer.contact": "Kontakt",
    "footer.other_products": "Weitere Produkte",
    "footer.kmu_suite": "KMU Suite",
    "footer.kmu_description": "Komplette Business-Management-Lösung",
    "footer.language": "Sprache",
    "footer.rights": "Alle Rechte vorbehalten",
    // Dashboard Home
    "dashboard.overview": "Übersicht",
    "dashboard.welcome": "Willkommen in Ihrem Rentably Dashboard",
    "dashboard.properties": "Immobilien",
    "dashboard.tenants.active": "Aktive Mieter",
    "dashboard.rent.monthly": "Monatliche Mieteinnahmen",
    "dashboard.yield.average": "Durchschnittliche Rendite",
    "dashboard.portfolio.total": "Gesamtübersicht",
    "dashboard.portfolio.value": "Gesamtwert Immobilien",
    "dashboard.portfolio.annual": "Jährliche Mieteinnahmen",
    "dashboard.quickstart": "Schnellstart",
    "dashboard.quickstart.description":
      "Beginnen Sie mit der Verwaltung Ihrer Immobilien, indem Sie Ihre erste Immobilie hinzufügen.",
    "dashboard.quickstart.property": "Immobilie anlegen",
    "dashboard.quickstart.tenant": "Mieter hinzufügen",
    "dashboard.quickstart.contract": "Mietvertrag hinterlegen",
    "dashboard.portal.title": "Mieter-Portal",
    "dashboard.portal.description":
      "Teilen Sie diesen Link mit Ihren Mietern, damit diese Tickets erstellen und den Status ihrer Anfragen verfolgen können.",
    "dashboard.portal.copy": "Link kopieren",
    "dashboard.portal.copied": "Link kopiert!",
    // Properties View
    "properties.title": "Immobilien",
    "properties.description": "Verwalten Sie Ihre Immobilien und deren Details",
    "properties.add": "Immobilie hinzufügen",
    "properties.empty.title": "Noch keine Immobilien",
    "properties.empty.description":
      "Fügen Sie Ihre erste Immobilie hinzu, um mit der Verwaltung zu beginnen.",
    "properties.add.first": "Erste Immobilie hinzufügen",
    "properties.rooms": "Zimmer",
    "properties.details": "Details ansehen",
    "properties.delete.confirm":
      "Möchten Sie diese Immobilie wirklich löschen?",
    // Property Details
    "property.back": "Zurück zur Übersicht",
    "property.analysis": "Finanzanalyse",
    "property.rooms": "Zimmer",
    "property.area": "Wohnfläche",
    "property.price.purchase": "Kaufpreis",
    "property.price.current": "Aktueller Wert",
    "property.price.sqm": "Preis pro m²",
    "property.yield.gross": "Bruttorendite",
    "property.yield.net": "Nettorendite",
    "property.yield.year": "pro Jahr",
    "property.yield.after.costs": "nach Kreditkosten",
    "property.cashflow.net": "Netto-Cashflow",
    "property.cashflow.month": "pro Monat",
    "property.loans.title": "Kredite & Finanzierungen",
    "property.loans.add": "Kredit hinzufügen",
    "property.loans.empty": "Noch keine Kredite hinterlegt",
    "property.loans.remaining": "verbleibend",
    "property.loans.interest": "Zinsen",
    "property.loans.monthly": "monatlich",
    "property.loans.delete.confirm":
      "Möchten Sie diesen Kredit wirklich löschen?",
    "property.tenants.title": "Mieter",
    "property.tenants.add": "Mieter hinzufügen",
    "property.tenants.empty": "Noch keine Mieter zugeordnet",
    "property.tenants.active": "Aktiv",
    "property.tenants.inactive": "Inaktiv",
    "property.yield.gross.calculation": "Berechnung Bruttorendite:",
    "property.yield.gross.formula":
      "Formel: (Jahresmiete ÷ Aktueller Wert) × 100",
    "property.yield.gross.monthly": "Monatliche Kaltmiete",
    "property.yield.gross.annual": "Jahresmiete",
    "property.yield.gross.value": "Aktueller Wert",
    "property.yield.net.calculation": "Berechnung Nettorendite:",
    "property.yield.net.formula":
      "Formel: (Netto-Jahreseinkommen ÷ Aktueller Wert) × 100",
    "property.yield.net.annual": "Jahresmiete",
    "property.yield.net.costs": "Jährliche Kreditkosten",
    "property.yield.net.income": "Netto-Jahreseinkommen",
    // Tenants View
    "tenants.title": "Mietverhältnisse",
    "tenants.description": "Verwalten Sie Ihre Mietverhältnisse und Mieter",
    "tenants.add": "Mietverhältnis hinzufügen",
    "tenants.empty.title": "Noch keine Mietverhältnisse",
    "tenants.empty.description":
      "Fügen Sie Ihr erstes Mietverhältnis hinzu, um mit der Verwaltung zu beginnen.",
    "tenants.add.first": "Erstes Mietverhältnis hinzufügen",
    "tenants.table.tenant": "Mieter",
    "tenants.table.property": "Immobilie",
    "tenants.table.contact": "Kontakt",
    "tenants.table.rent": "Kaltmiete",
    "tenants.table.status": "Status",
    "tenants.table.actions": "Aktionen",
    "tenants.moved.in": "Eingezogen",
    "tenants.not.assigned": "Nicht zugeordnet",
    "tenants.contract.add": "Vertrag hinzufügen",
    "tenants.status.active": "Aktiv",
    "tenants.status.inactive": "Inaktiv",
    "tenants.contract.edit": "Vertrag bearbeiten",
    "tenants.delete.confirm": "Möchten Sie diesen Mieter wirklich löschen?",
    // Rent Payments View
    "payments.title": "Mieteingänge",
    "payments.description": "Verwalten Sie ausstehende und bezahlte Mieten",
    "payments.loading": "Lade Mieteingänge...",
    "payments.outstanding": "Ausstehend",
    "payments.paid": "Bezahlt",
    "payments.total": "Gesamt",
    "payments.filter": "Filter",
    "payments.filter.property": "Immobilie",
    "payments.filter.tenant": "Mieter",
    "payments.filter.status": "Status",
    "payments.filter.from": "Von",
    "payments.filter.to": "Bis",
    "payments.filter.all": "Alle",
    "payments.filter.unpaid": "Ausstehend",
    "payments.filter.paid": "Bezahlt",
    "payments.empty":
      "Keine Mieteingänge gefunden. Mieteingänge werden automatisch generiert, wenn Sie Mietverträge anlegen.",
    "payments.table.due": "Fälligkeitsdatum",
    "payments.table.property": "Immobilie",
    "payments.table.tenant": "Mieter",
    "payments.table.amount": "Betrag",
    "payments.table.status": "Status",
    "payments.table.action": "Aktion",
    "payments.status.paid": "Bezahlt",
    "payments.status.outstanding": "Ausstehend",
    "payments.mark.paid": "Als bezahlt markieren",
    "payments.mark.unpaid": "Als unbezahlt markieren",
    "payments.error.marking": "Fehler beim Markieren der Zahlung",
    // Tickets View
    "tickets.title": "Tickets",
    "tickets.description":
      "Verwalten Sie Anfragen und Nachrichten Ihrer Mieter",
    "tickets.create": "Ticket erstellen",
    "tickets.filter.all": "Alle",
    "tickets.filter.open": "Offen",
    "tickets.filter.progress": "In Bearbeitung",
    "tickets.filter.closed": "Geschlossen",
    "tickets.empty.title": "Noch keine Tickets",
    "tickets.empty.all":
      "Erstellen Sie Ihr erstes Ticket oder warten Sie auf Anfragen von Mietern.",
    "tickets.empty.filter": "Es gibt keine Tickets mit dem Status",
    "tickets.create.first": "Erstes Ticket erstellen",
    "tickets.status.open": "Offen",
    "tickets.status.progress": "In Bearbeitung",
    "tickets.status.closed": "Geschlossen",
    "tickets.priority.urgent": "Dringend",
    "tickets.priority.high": "Hoch",
    "tickets.priority.medium": "Mittel",
    "tickets.priority.low": "Niedrig",
    // Ticket Details
    "ticket.back": "Zurück zur Übersicht",
    "ticket.status.progress": "In Bearbeitung",
    "ticket.status.close": "Schließen",
    "ticket.status.reopen": "Wieder öffnen",
    "ticket.messages.title": "Nachrichtenverlauf",
    "ticket.messages.empty": "Noch keine Nachrichten",
    "ticket.message.placeholder": "Nachricht schreiben...",
    "ticket.message.send": "Senden",
    "ticket.error.status": "Fehler beim Aktualisieren des Status",
    "ticket.error.send": "Fehler beim Senden der Nachricht",
    // Financial Analysis View
    "financial.title": "Finanzanalyse",
    "financial.description": "Aktuelle Zahlen und Zukunftsprognosen",
    "financial.current": "IST-Stand",
    "financial.projection": "Prognose",
    "financial.income.annual": "Jährliche Mieteinnahmen",
    "financial.expenses.annual": "Jährliche Ausgaben",
    "financial.net.income": "Nettoeinkommen (Jahr)",
    "financial.income.monthly.title": "Monatliche Einnahmen",
    "financial.income.rent": "Kaltmiete",
    "financial.income.total": "Gesamt",
    "financial.expenses.monthly.title": "Monatliche Ausgaben",
    "financial.expenses.loans": "Kreditraten",
    "financial.expenses.total": "Gesamt",
    "financial.projection.settings": "Prognose-Einstellungen",
    "financial.projection.years": "Prognosezeitraum",
    "financial.projection.years.label": "Jahre",
    "financial.projection.rent.increase": "Mietsteigerung p.a.",
    "financial.projection.cost.increase": "Kostensteigerung p.a.",
    "financial.projection.table.year": "Jahr",
    "financial.projection.table.revenue": "Einnahmen",
    "financial.projection.table.expenses": "Ausgaben",
    "financial.projection.table.net": "Nettoeinkommen",
    "financial.projection.table.cumulative": "Kumuliert",
    "financial.projection.table.total": "Gesamt",
    "financial.projection.note": "Hinweis zur Prognose:",
    "financial.projection.disclaimer":
      "Diese Prognose basiert auf den aktuellen Daten und den eingestellten jährlichen Steigerungsraten. Tatsächliche Ergebnisse können aufgrund von Marktveränderungen, Leerständen, Sonderausgaben und anderen Faktoren abweichen.",
    // Property Modal
    "modal.property.title.edit": "Immobilie bearbeiten",
    "modal.property.title.new": "Neue Immobilie",
    "modal.property.name": "Bezeichnung",
    "modal.property.name.placeholder": "z.B. Wohnung Musterstraße 1",
    "modal.property.street": "Straße und Hausnummer",
    "modal.property.street.placeholder": "z.B. Musterstraße 1",
    "modal.property.zip": "PLZ",
    "modal.property.zip.placeholder": "z.B. 12345",
    "modal.property.city": "Stadt",
    "modal.property.city.placeholder": "z.B. Berlin",
    "modal.property.type": "Immobilientyp",
    "modal.property.type.apartment": "Wohnung",
    "modal.property.type.house": "Haus",
    "modal.property.type.commercial": "Gewerbe",
    "modal.property.type.land": "Grundstück",
    "modal.property.date.purchase": "Kaufdatum",
    "modal.property.price.purchase": "Kaufpreis (€)",
    "modal.property.price.purchase.placeholder": "z.B. 250000 oder 250.000,50",
    "modal.property.price.current": "Aktueller Wert (€)",
    "modal.property.price.current.placeholder": "z.B. 280000 oder 280.000,00",
    "modal.property.area": "Wohnfläche (m²)",
    "modal.property.area.placeholder": "z.B. 75,5",
    "modal.property.rooms": "Anzahl Zimmer",
    "modal.property.rooms.placeholder": "z.B. 3 oder 3,5",
    "modal.property.description": "Beschreibung",
    "modal.property.description.placeholder": "Zusätzliche Informationen...",
    "modal.property.error": "Fehler beim Speichern der Immobilie",
    // Tenant Modal
    "modal.tenant.title.edit": "Mieter bearbeiten",
    "modal.tenant.title.new": "Neuer Mieter",
    "modal.tenant.property": "Immobilie",
    "modal.tenant.property.select": "Bitte wählen...",
    "modal.tenant.firstname": "Vorname",
    "modal.tenant.lastname": "Nachname",
    "modal.tenant.email": "E-Mail",
    "modal.tenant.phone": "Telefon",
    "modal.tenant.movein": "Einzugsdatum",
    "modal.tenant.moveout": "Auszugsdatum",
    "modal.tenant.active": "Aktiver Mieter",
    "modal.tenant.error": "Fehler beim Speichern des Mieters",
    // Contract Modal
    "modal.contract.title.edit": "Mietvertrag bearbeiten",
    "modal.contract.title.new": "Neuer Mietvertrag",
    "modal.contract.tenant": "Mieter",
    "modal.contract.rent.title": "Miete",
    "modal.contract.rent.base": "Kaltmiete (€)",
    "modal.contract.rent.base.placeholder": "z.B. 850 oder 850,50",
    "modal.contract.rent.additional": "Nebenkosten (€)",
    "modal.contract.rent.additional.placeholder": "z.B. 150 oder 150,75",
    "modal.contract.rent.total": "Warmmiete (gesamt)",
    "modal.contract.deposit": "Kaution (€)",
    "modal.contract.deposit.placeholder": "z.B. 2550 oder 2550,00",
    "modal.contract.increase.title": "Mieterhöhung",
    "modal.contract.increase.type": "Art der Mieterhöhung",
    "modal.contract.increase.none": "Keine",
    "modal.contract.increase.staffel": "Staffelmiete",
    "modal.contract.increase.index": "Indexmiete",
    "modal.contract.increase.amount": "Erhöhung pro Jahr",
    "modal.contract.increase.amount.placeholder": "z.B. 2,5",
    "modal.contract.increase.type.label": "Typ",
    "modal.contract.increase.type.percentage": "Prozent (%)",
    "modal.contract.increase.type.fixed": "Fester Betrag (€)",
    "modal.contract.increase.years": "Anzahl Jahre",
    "modal.contract.increase.years.placeholder": "z.B. 5",
    "modal.contract.increase.first": "Erster Erhöhungszeitpunkt",
    "modal.contract.details.title": "Vertragsdaten",
    "modal.contract.start": "Vertragsbeginn",
    "modal.contract.end": "Vertragsende",
    "modal.contract.type": "Vertragsart",
    "modal.contract.type.unlimited": "Unbefristet",
    "modal.contract.type.fixed": "Befristet",
    "modal.contract.document": "Mietvertrag (Dokument)",
    "modal.contract.document.select": "Datei auswählen",
    "modal.contract.document.exists": "Dokument vorhanden",
    "modal.contract.document.info": "PDF, Word oder Bild (max. 10MB)",
    "modal.contract.notes": "Notizen",
    "modal.contract.notes.placeholder": "Zusätzliche Informationen...",
    "modal.contract.error.save": "Fehler beim Speichern des Mietvertrags",
    "modal.contract.error.upload": "Fehler beim Hochladen des Dokuments",
    // Ticket Modal
    "modal.ticket.title.edit": "Ticket bearbeiten",
    "modal.ticket.title.new": "Neues Ticket",
    "modal.ticket.property": "Immobilie",
    "modal.ticket.property.select": "Bitte wählen...",
    "modal.ticket.tenant": "Mieter",
    "modal.ticket.tenant.none": "Kein Mieter zugeordnet",
    "modal.ticket.subject": "Betreff",
    "modal.ticket.subject.placeholder": "z.B. Heizung defekt",
    "modal.ticket.category": "Kategorie",
    "modal.ticket.category.general": "Allgemein",
    "modal.ticket.category.maintenance": "Wartung",
    "modal.ticket.category.repair": "Reparatur",
    "modal.ticket.category.complaint": "Beschwerde",
    "modal.ticket.category.question": "Frage",
    "modal.ticket.priority": "Priorität",
    "modal.ticket.priority.low": "Niedrig",
    "modal.ticket.priority.medium": "Mittel",
    "modal.ticket.priority.high": "Hoch",
    "modal.ticket.priority.urgent": "Dringend",
    "modal.ticket.status": "Status",
    "modal.ticket.status.open": "Offen",
    "modal.ticket.status.progress": "In Bearbeitung",
    "modal.ticket.status.closed": "Geschlossen",
    "modal.ticket.message": "Beschreibung",
    "modal.ticket.message.add": "Nachricht hinzufügen",
    "modal.ticket.message.placeholder": "Beschreiben Sie das Anliegen...",
    "modal.ticket.error": "Fehler beim Speichern des Tickets",
    // Loan Modal
    "modal.loan.title.edit": "Kredit bearbeiten",
    "modal.loan.title.new": "Neuer Kredit",
    "modal.loan.lender": "Kreditgeber",
    "modal.loan.lender.placeholder": "z.B. Sparkasse",
    "modal.loan.amount": "Kreditsumme (€)",
    "modal.loan.amount.placeholder": "z.B. 200000 oder 200.000,00",
    "modal.loan.balance": "Restschuld (€)",
    "modal.loan.balance.placeholder": "z.B. 185000 oder 185.000,00",
    "modal.loan.rate": "Zinssatz (%)",
    "modal.loan.rate.placeholder": "z.B. 2,5 oder 2.5",
    "modal.loan.payment": "Monatliche Rate (€)",
    "modal.loan.payment.placeholder": "z.B. 1200 oder 1200,50",
    "modal.loan.principal": "Monatliche Tilgung (€)",
    "modal.loan.principal.placeholder": "z.B. 800 oder 800,00",
    "modal.loan.principal.info":
      "Tilgungsanteil der monatlichen Rate (Rate - Zinsen)",
    "modal.loan.start": "Kreditbeginn",
    "modal.loan.end": "Kreditende",
    "modal.loan.type": "Kreditart",
    "modal.loan.type.mortgage": "Hypothek",
    "modal.loan.type.renovation": "Renovierungskredit",
    "modal.loan.type.other": "Sonstiges",
    "modal.loan.notes": "Notizen",
    "modal.loan.notes.placeholder": "Zusätzliche Informationen...",
    "modal.loan.error": "Fehler beim Speichern des Kredits",
    // Common Modal Actions
    "modal.cancel": "Abbrechen",
    "modal.save": "Speichern",
    "modal.saving": "Speichern...",
    "modal.uploading": "Hochladen...",
    "common.required": "*",
    "common.loading": "Lädt...",
  },
  en: {
    "nav.overview": "Overview",
    "nav.properties": "Properties",
    "nav.tenants": "Rental Contracts",
    "nav.payments": "Rent Payments",
    "nav.tickets": "Tickets",
    "nav.financial": "Finances",
    "nav.documents": "Documents",
    "nav.billing": "Billing",
    "nav.account": "Account",
    "nav.languages": "Languages",
    "nav.logout": "Logout",
    "settings.profile": "Profile",
    "settings.users": "User Management",
    "settings.billing": "Plan & Billing",
    "settings.feedback": "Feedback",
    "settings.language": "Language",
    "settings.email": "Email",
    "settings.plan": "Current Plan",
    "settings.plan.free": "Free",
    "settings.plan.pro": "Professional",
    "settings.plan.enterprise": "Enterprise",
    "settings.billing.company": "Company Information",
    "settings.billing.name": "Company Name",
    "settings.billing.vat": "VAT ID",
    "settings.billing.address": "Billing Address",
    "settings.billing.payment": "Payment Method",
    "settings.billing.invoices": "Invoices",
    "settings.users.invite": "Invite User",
    "settings.users.email": "Email Address",
    "settings.users.status": "Status",
    "settings.users.role": "Role",
    "settings.users.actions": "Actions",
    "settings.users.pending": "Pending",
    "settings.users.accepted": "Active",
    "settings.users.admin": "Administrator",
    "settings.users.member": "Member",
    "settings.users.viewer": "View Only",
    "settings.users.delete": "Delete",
    "settings.users.invite.button": "Invite",
    "settings.users.invite.success": "Invitation sent successfully",
    "settings.feedback.title": "Feature Requests & Feedback",
    "settings.feedback.description": "Share your ideas and suggestions with us",
    "settings.feedback.idea": "Your Idea",
    "settings.feedback.idea.placeholder": "Describe your idea or suggestion...",
    "settings.feedback.willing_to_pay": "Willing to pay for it?",
    "settings.feedback.willing_to_pay.yes": "Yes",
    "settings.feedback.willing_to_pay.no": "No",
    "settings.feedback.amount": "How much would you be willing to pay?",
    "settings.feedback.amount.placeholder": "e.g. 10 EUR per month",
    "settings.feedback.submit": "Submit Feedback",
    "settings.feedback.success": "Thank you for your feedback!",
    "settings.feedback.history": "Your Feedback",
    "settings.feedback.date": "Date",
    "settings.feedback.status": "Status",
    "settings.feedback.status.pending": "Under Review",
    "settings.feedback.status.reviewed": "Reviewed",
    "settings.feedback.status.planned": "Planned",
    "settings.feedback.status.implemented": "Implemented",
    "feedback.menu": "Feedback & Ideas",
    "feedback.title": "Feature Suggestions & Ideas",
    "feedback.description": "Share your ideas or vote on existing suggestions",
    "feedback.submit": "Submit New Idea",
    "feedback.filter.all": "All",
    "feedback.filter.top": "Top Rated",
    "feedback.filter.new": "Newest",
    "feedback.filter.mine": "My Ideas",
    "feedback.votes": "Votes",
    "feedback.no_feedback": "No suggestions yet",
    "feedback.submit_first": "Be the first to share your idea!",
    "referral.title": "Referral Program",
    "referral.description": "Refer Rentably and earn rewards!",
    "referral.learn_more": "Learn more",
    "footer.product": "Product",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.other_products": "Other Products",
    "footer.kmu_suite": "KMU Suite",
    "footer.kmu_description": "Complete business management solution",
    "footer.language": "Language",
    "footer.rights": "All rights reserved",
    // Dashboard Home
    "dashboard.overview": "Overview",
    "dashboard.welcome": "Welcome to your Rentably Dashboard",
    "dashboard.properties": "Properties",
    "dashboard.tenants.active": "Active Tenants",
    "dashboard.rent.monthly": "Monthly Rental Income",
    "dashboard.yield.average": "Average Yield",
    "dashboard.portfolio.total": "Total Overview",
    "dashboard.portfolio.value": "Total Property Value",
    "dashboard.portfolio.annual": "Annual Rental Income",
    "dashboard.quickstart": "Quick Start",
    "dashboard.quickstart.description":
      "Start managing your properties by adding your first property.",
    "dashboard.quickstart.property": "Add Property",
    "dashboard.quickstart.tenant": "Add Tenant",
    "dashboard.quickstart.contract": "Add Lease Agreement",
    "dashboard.portal.title": "Tenant Portal",
    "dashboard.portal.description":
      "Share this link with your tenants so they can create tickets and track the status of their requests.",
    "dashboard.portal.copy": "Copy Link",
    "dashboard.portal.copied": "Link Copied!",
    // Properties View
    "properties.title": "Properties",
    "properties.description": "Manage your properties and their details",
    "properties.add": "Add Property",
    "properties.empty.title": "No Properties Yet",
    "properties.empty.description":
      "Add your first property to start managing.",
    "properties.add.first": "Add First Property",
    "properties.rooms": "Rooms",
    "properties.details": "View Details",
    "properties.delete.confirm": "Do you really want to delete this property?",
    // Property Details
    "property.back": "Back to Overview",
    "property.analysis": "Financial Analysis",
    "property.rooms": "Rooms",
    "property.area": "Living Area",
    "property.price.purchase": "Purchase Price",
    "property.price.current": "Current Value",
    "property.price.sqm": "Price per sqm",
    "property.yield.gross": "Gross Yield",
    "property.yield.net": "Net Yield",
    "property.yield.year": "per year",
    "property.yield.after.costs": "after loan costs",
    "property.cashflow.net": "Net Cashflow",
    "property.cashflow.month": "per month",
    "property.loans.title": "Loans & Financing",
    "property.loans.add": "Add Loan",
    "property.loans.empty": "No loans recorded yet",
    "property.loans.remaining": "remaining",
    "property.loans.interest": "Interest",
    "property.loans.monthly": "monthly",
    "property.loans.delete.confirm": "Do you really want to delete this loan?",
    "property.tenants.title": "Tenants",
    "property.tenants.add": "Add Tenant",
    "property.tenants.empty": "No tenants assigned yet",
    "property.tenants.active": "Active",
    "property.tenants.inactive": "Inactive",
    "property.yield.gross.calculation": "Gross Yield Calculation:",
    "property.yield.gross.formula":
      "Formula: (Annual Rent ÷ Current Value) × 100",
    "property.yield.gross.monthly": "Monthly Base Rent",
    "property.yield.gross.annual": "Annual Rent",
    "property.yield.gross.value": "Current Value",
    "property.yield.net.calculation": "Net Yield Calculation:",
    "property.yield.net.formula":
      "Formula: (Net Annual Income ÷ Current Value) × 100",
    "property.yield.net.annual": "Annual Rent",
    "property.yield.net.costs": "Annual Loan Costs",
    "property.yield.net.income": "Net Annual Income",
    // Tenants View
    "tenants.title": "Rental Contracts",
    "tenants.description": "Manage your rental contracts and tenants",
    "tenants.add": "Add Rental Contract",
    "tenants.empty.title": "No Rental Contracts Yet",
    "tenants.empty.description":
      "Add your first rental contract to start managing.",
    "tenants.add.first": "Add First Rental Contract",
    "tenants.table.tenant": "Tenant",
    "tenants.table.property": "Property",
    "tenants.table.contact": "Contact",
    "tenants.table.rent": "Base Rent",
    "tenants.table.status": "Status",
    "tenants.table.actions": "Actions",
    "tenants.moved.in": "Moved In",
    "tenants.not.assigned": "Not Assigned",
    "tenants.contract.add": "Add Contract",
    "tenants.status.active": "Active",
    "tenants.status.inactive": "Inactive",
    "tenants.contract.edit": "Edit Contract",
    "tenants.delete.confirm": "Do you really want to delete this tenant?",
    // Rent Payments View
    "payments.title": "Rent Payments",
    "payments.description": "Manage outstanding and paid rents",
    "payments.loading": "Loading rent payments...",
    "payments.outstanding": "Outstanding",
    "payments.paid": "Paid",
    "payments.total": "Total",
    "payments.filter": "Filter",
    "payments.filter.property": "Property",
    "payments.filter.tenant": "Tenant",
    "payments.filter.status": "Status",
    "payments.filter.from": "From",
    "payments.filter.to": "To",
    "payments.filter.all": "All",
    "payments.filter.unpaid": "Outstanding",
    "payments.filter.paid": "Paid",
    "payments.empty":
      "No rent payments found. Rent payments are automatically generated when you create lease agreements.",
    "payments.table.due": "Due Date",
    "payments.table.property": "Property",
    "payments.table.tenant": "Tenant",
    "payments.table.amount": "Amount",
    "payments.table.status": "Status",
    "payments.table.action": "Action",
    "payments.status.paid": "Paid",
    "payments.status.outstanding": "Outstanding",
    "payments.mark.paid": "Mark as Paid",
    "payments.mark.unpaid": "Mark as Unpaid",
    "payments.error.marking": "Error marking payment",
    // Tickets View
    "tickets.title": "Tickets",
    "tickets.description": "Manage requests and messages from your tenants",
    "tickets.create": "Create Ticket",
    "tickets.filter.all": "All",
    "tickets.filter.open": "Open",
    "tickets.filter.progress": "In Progress",
    "tickets.filter.closed": "Closed",
    "tickets.empty.title": "No Tickets Yet",
    "tickets.empty.all":
      "Create your first ticket or wait for requests from tenants.",
    "tickets.empty.filter": "There are no tickets with the status",
    "tickets.create.first": "Create First Ticket",
    "tickets.status.open": "Open",
    "tickets.status.progress": "In Progress",
    "tickets.status.closed": "Closed",
    "tickets.priority.urgent": "Urgent",
    "tickets.priority.high": "High",
    "tickets.priority.medium": "Medium",
    "tickets.priority.low": "Low",
    // Ticket Details
    "ticket.back": "Back to Overview",
    "ticket.status.progress": "In Progress",
    "ticket.status.close": "Close",
    "ticket.status.reopen": "Reopen",
    "ticket.messages.title": "Message History",
    "ticket.messages.empty": "No messages yet",
    "ticket.message.placeholder": "Write a message...",
    "ticket.message.send": "Send",
    "ticket.error.status": "Error updating status",
    "ticket.error.send": "Error sending message",
    // Financial Analysis View
    "financial.title": "Financial Analysis",
    "financial.description": "Current figures and future projections",
    "financial.current": "Current Status",
    "financial.projection": "Projection",
    "financial.income.annual": "Annual Rental Income",
    "financial.expenses.annual": "Annual Expenses",
    "financial.net.income": "Net Income (Annual)",
    "financial.income.monthly.title": "Monthly Income",
    "financial.income.rent": "Base Rent",
    "financial.income.total": "Total",
    "financial.expenses.monthly.title": "Monthly Expenses",
    "financial.expenses.loans": "Loan Payments",
    "financial.expenses.total": "Total",
    "financial.projection.settings": "Projection Settings",
    "financial.projection.years": "Projection Period",
    "financial.projection.years.label": "Years",
    "financial.projection.rent.increase": "Rent Increase p.a.",
    "financial.projection.cost.increase": "Cost Increase p.a.",
    "financial.projection.table.year": "Year",
    "financial.projection.table.revenue": "Revenue",
    "financial.projection.table.expenses": "Expenses",
    "financial.projection.table.net": "Net Income",
    "financial.projection.table.cumulative": "Cumulative",
    "financial.projection.table.total": "Total",
    "financial.projection.note": "Note on Projection:",
    "financial.projection.disclaimer":
      "This projection is based on current data and the set annual increase rates. Actual results may vary due to market changes, vacancies, extraordinary expenses, and other factors.",
    // Property Modal
    "modal.property.title.edit": "Edit Property",
    "modal.property.title.new": "New Property",
    "modal.property.name": "Name",
    "modal.property.name.placeholder": "e.g. Apartment Main Street 1",
    "modal.property.street": "Street and Number",
    "modal.property.street.placeholder": "e.g. Main Street 1",
    "modal.property.zip": "ZIP Code",
    "modal.property.zip.placeholder": "e.g. 12345",
    "modal.property.city": "City",
    "modal.property.city.placeholder": "e.g. Berlin",
    "modal.property.type": "Property Type",
    "modal.property.type.apartment": "Apartment",
    "modal.property.type.house": "House",
    "modal.property.type.commercial": "Commercial",
    "modal.property.type.land": "Land",
    "modal.property.date.purchase": "Purchase Date",
    "modal.property.price.purchase": "Purchase Price (€)",
    "modal.property.price.purchase.placeholder": "e.g. 250000 or 250,000.50",
    "modal.property.price.current": "Current Value (€)",
    "modal.property.price.current.placeholder": "e.g. 280000 or 280,000.00",
    "modal.property.area": "Living Area (sqm)",
    "modal.property.area.placeholder": "e.g. 75.5",
    "modal.property.rooms": "Number of Rooms",
    "modal.property.rooms.placeholder": "e.g. 3 or 3.5",
    "modal.property.description": "Description",
    "modal.property.description.placeholder": "Additional information...",
    "modal.property.error": "Error saving property",
    // Tenant Modal
    "modal.tenant.title.edit": "Edit Tenant",
    "modal.tenant.title.new": "New Tenant",
    "modal.tenant.property": "Property",
    "modal.tenant.property.select": "Please select...",
    "modal.tenant.firstname": "First Name",
    "modal.tenant.lastname": "Last Name",
    "modal.tenant.email": "Email",
    "modal.tenant.phone": "Phone",
    "modal.tenant.movein": "Move-in Date",
    "modal.tenant.moveout": "Move-out Date",
    "modal.tenant.active": "Active Tenant",
    "modal.tenant.error": "Error saving tenant",
    // Contract Modal
    "modal.contract.title.edit": "Edit Lease Agreement",
    "modal.contract.title.new": "New Lease Agreement",
    "modal.contract.tenant": "Tenant",
    "modal.contract.rent.title": "Rent",
    "modal.contract.rent.base": "Base Rent (€)",
    "modal.contract.rent.base.placeholder": "e.g. 850 or 850.50",
    "modal.contract.rent.additional": "Additional Costs (€)",
    "modal.contract.rent.additional.placeholder": "e.g. 150 or 150.75",
    "modal.contract.rent.total": "Total Rent",
    "modal.contract.deposit": "Deposit (€)",
    "modal.contract.deposit.placeholder": "e.g. 2550 or 2550.00",
    "modal.contract.increase.title": "Rent Increase",
    "modal.contract.increase.type": "Type of Rent Increase",
    "modal.contract.increase.none": "None",
    "modal.contract.increase.staffel": "Graduated Rent",
    "modal.contract.increase.index": "Index Rent",
    "modal.contract.increase.amount": "Increase per Year",
    "modal.contract.increase.amount.placeholder": "e.g. 2.5",
    "modal.contract.increase.type.label": "Type",
    "modal.contract.increase.type.percentage": "Percentage (%)",
    "modal.contract.increase.type.fixed": "Fixed Amount (€)",
    "modal.contract.increase.years": "Number of Years",
    "modal.contract.increase.years.placeholder": "e.g. 5",
    "modal.contract.increase.first": "First Increase Date",
    "modal.contract.details.title": "Contract Details",
    "modal.contract.start": "Contract Start",
    "modal.contract.end": "Contract End",
    "modal.contract.type": "Contract Type",
    "modal.contract.type.unlimited": "Unlimited",
    "modal.contract.type.fixed": "Fixed Term",
    "modal.contract.document": "Lease Agreement (Document)",
    "modal.contract.document.select": "Select File",
    "modal.contract.document.exists": "Document Available",
    "modal.contract.document.info": "PDF, Word or Image (max. 10MB)",
    "modal.contract.notes": "Notes",
    "modal.contract.notes.placeholder": "Additional information...",
    "modal.contract.error.save": "Error saving lease agreement",
    "modal.contract.error.upload": "Error uploading document",
    // Ticket Modal
    "modal.ticket.title.edit": "Edit Ticket",
    "modal.ticket.title.new": "New Ticket",
    "modal.ticket.property": "Property",
    "modal.ticket.property.select": "Please select...",
    "modal.ticket.tenant": "Tenant",
    "modal.ticket.tenant.none": "No tenant assigned",
    "modal.ticket.subject": "Subject",
    "modal.ticket.subject.placeholder": "e.g. Heating broken",
    "modal.ticket.category": "Category",
    "modal.ticket.category.general": "General",
    "modal.ticket.category.maintenance": "Maintenance",
    "modal.ticket.category.repair": "Repair",
    "modal.ticket.category.complaint": "Complaint",
    "modal.ticket.category.question": "Question",
    "modal.ticket.priority": "Priority",
    "modal.ticket.priority.low": "Low",
    "modal.ticket.priority.medium": "Medium",
    "modal.ticket.priority.high": "High",
    "modal.ticket.priority.urgent": "Urgent",
    "modal.ticket.status": "Status",
    "modal.ticket.status.open": "Open",
    "modal.ticket.status.progress": "In Progress",
    "modal.ticket.status.closed": "Closed",
    "modal.ticket.message": "Description",
    "modal.ticket.message.add": "Add Message",
    "modal.ticket.message.placeholder": "Describe the issue...",
    "modal.ticket.error": "Error saving ticket",
    // Loan Modal
    "modal.loan.title.edit": "Edit Loan",
    "modal.loan.title.new": "New Loan",
    "modal.loan.lender": "Lender",
    "modal.loan.lender.placeholder": "e.g. Sparkasse",
    "modal.loan.amount": "Loan Amount (€)",
    "modal.loan.amount.placeholder": "e.g. 200000 or 200,000.00",
    "modal.loan.balance": "Remaining Balance (€)",
    "modal.loan.balance.placeholder": "e.g. 185000 or 185,000.00",
    "modal.loan.rate": "Interest Rate (%)",
    "modal.loan.rate.placeholder": "e.g. 2.5 or 2.5",
    "modal.loan.payment": "Monthly Payment (€)",
    "modal.loan.payment.placeholder": "e.g. 1200 or 1200.50",
    "modal.loan.principal": "Monthly Principal (€)",
    "modal.loan.principal.placeholder": "e.g. 800 or 800.00",
    "modal.loan.principal.info":
      "Principal portion of monthly payment (Payment - Interest)",
    "modal.loan.start": "Loan Start",
    "modal.loan.end": "Loan End",
    "modal.loan.type": "Loan Type",
    "modal.loan.type.mortgage": "Mortgage",
    "modal.loan.type.renovation": "Renovation Loan",
    "modal.loan.type.other": "Other",
    "modal.loan.notes": "Notes",
    "modal.loan.notes.placeholder": "Additional information...",
    "modal.loan.error": "Error saving loan",
    // Common Modal Actions
    "modal.cancel": "Cancel",
    "modal.save": "Save",
    "modal.saving": "Saving...",
    "modal.uploading": "Uploading...",
    "common.required": "*",
    "common.loading": "Loading...",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>("de");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("rentably_language") as Language;
    if (savedLanguage && (savedLanguage === "de" || savedLanguage === "en")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  useEffect(() => {
    if (user) {
      loadUserLanguage();
    }
  }, [user]);

  const loadUserLanguage = async () => {
    if (!user) return;

    try {
      const { data } = await supabase
        .from("user_settings")
        .select("language")
        .eq("user_id", user.id)
        .maybeSingle();

      if (
        data?.language &&
        (data.language === "de" || data.language === "en")
      ) {
        setLanguageState(data.language as Language);
        localStorage.setItem("rentably_language", data.language);
      }
    } catch (error) {
      console.error("Error loading user language:", error);
    }
  };

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("rentably_language", lang);

    if (user) {
      try {
        await supabase
          .from("user_settings")
          .update({ language: lang })
          .eq("user_id", user.id);
      } catch (error) {
        console.error("Error saving user language:", error);
      }
    }
  };

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)["de"]] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
